// Loads the demo fixtures generated by the backend's `export` profile (real engine output).
// Bundled at build time so the GitHub Pages deployment is a fully working demo with no backend.
import type { Agent, Policy, RunDetail, ScenarioInfo } from '../types';

import scenarios from './fixtures/scenarios.json';
import agents from './fixtures/agents.json';
import policies from './fixtures/policies.json';

import normalDevelopment from './fixtures/runs/normal-development.json';
import promptInjection from './fixtures/runs/prompt-injection.json';
import secretExposure from './fixtures/runs/secret-exposure.json';
import privilegeEscalation from './fixtures/runs/privilege-escalation.json';
import compromisedAgent from './fixtures/runs/compromised-agent.json';
import abnormalFileAccess from './fixtures/runs/abnormal-file-access.json';

export const demoScenarios = scenarios as unknown as ScenarioInfo[];
export const demoAgents = agents as unknown as Agent[];
export const demoPolicies = policies as unknown as Policy[];

// Keyed by scenarioId so a "run" of a scenario resolves to its precomputed detail.
export const demoRunsByScenario: Record<string, RunDetail> = {
  'normal-development': normalDevelopment as unknown as RunDetail,
  'prompt-injection': promptInjection as unknown as RunDetail,
  'secret-exposure': secretExposure as unknown as RunDetail,
  'privilege-escalation': privilegeEscalation as unknown as RunDetail,
  'compromised-agent': compromisedAgent as unknown as RunDetail,
  'abnormal-file-access': abnormalFileAccess as unknown as RunDetail,
};

export const demoRunList: RunDetail[] = Object.values(demoRunsByScenario);
